### PR TITLE
Allow psr container v2

### PR DESCRIPTION
**Pull request by hannesvdvreken**
Only requires new minor version.

See hannesvdvreken/psr-container-v2-demonstrator#1 for an explanation.

### CODE REVIEW

**Comment by Lctrs** [comment]
Waiting for a new version of `fakerphp/faker` supporting `psr/container` v2 before working on this. We'll likely drop support for `psr/container` v1 as I have a policy of not supporting more than 1 major version of a dependency (except for PHP itself).

**Comment by hannesvdvreken** [comment]
> Waiting for a new version of fakerphp/faker supporting psr/container v2 before working on this.

I wanted to help with that but [looks like](https://github.com/FakerPHP/Faker/pull/354) it's already sorted.

> We'll likely drop support for psr/container v1 as I have a policy of not supporting more than 1 major version of a dependency (except for PHP itself).

PSR is almost like PHP isn't it? Fine by me though.

**Comment by hannesvdvreken** [comment]
resolved merge confict

**Comment by Lctrs** [comment]
Superseded by #302

**Pull request closed without merging**
